"""Scheduler data-source interface: table-lookup recommendation + recording results.

A unified interface backs multiple sources, fully decoupling the scheduling core
from storage:

- BuiltinRegistry   -- rule fallback (conservative choice with no external table, read-only)
- MemoryRegistry    -- in-memory mapping table (tests / one-off tasks)
- FileRegistry      -- read-only static parameter table (imported from file or website, for cold start)
- LocalCacheRegistry-- writable local cache (the user's own experience table, getting better with use)
"""

from __future__ import annotations

import json
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

from .capabilities import decision_class, eligible_methods


class BackendRegistry(ABC):
    """Unified interface between the scheduler and external data sources."""

    @abstractmethod
    def get_recommendation(self, features: dict[str, Any]) -> str | None:
        """Return the recommended backend name for the circuit features; return None if no match."""

    def report_result(
        self,
        features: dict[str, Any],
        backend_name: str,
        duration: float,
        memory: Any | None,
    ) -> None:
        """Record one run result for future scheduling optimization (no-op by default)."""
        return


class BuiltinRegistry(BackendRegistry):
    """Built-in rule fallback: conservative choice when no external table exists."""

    def get_recommendation(self, features: dict[str, Any]) -> str:
        # QPanda is fastest for most circuits based on Experiment 2b benchmarks
        return "qpanda"

    def __repr__(self) -> str:
        return "BuiltinRegistry()"


# Cold-start fallback thresholds: empirical crossover points from Experiments 2b/11.
# QPanda is fastest for most circuits; qiskit/stabilizer for large Clifford.
_DEFAULT_DECISION: dict[str, dict[str, Any]] = {
    "clifford": {"method": "stabilizer", "above_n": 20, "backend": "qiskit"},
    "low_tw": {"method": "matrix_product_state", "above_n": 20, "backend": "native"},
}


@dataclass(frozen=True)
class Recommendation:
    """Scheduling decision result: backend name + simulation method."""

    backend: str
    method: str = "statevector"


_benchmark_cache: dict[str, Any] | None = None  # None = not loaded yet


def _load_benchmarks() -> dict[str, Any]:
    """Read the entire data/benchmarks.json; return an empty dict if missing or unparsable."""
    global _benchmark_cache
    if _benchmark_cache is None:
        try:
            import json
            import os

            path = os.path.join(os.path.dirname(__file__), "data", "benchmarks.json")
            with open(path, encoding="utf-8") as f:
                _benchmark_cache = json.load(f)
        except (OSError, ValueError):
            _benchmark_cache = {}
    return _benchmark_cache


def load_measured_decision() -> dict[str, Any]:
    """Load the measured decision table (decision field); return an empty dict if missing or unparsable."""
    return _load_benchmarks().get("decision", {})


def load_performance() -> list[Any]:
    """Load measured performance data (performance field); return an empty list if missing."""
    return _load_benchmarks().get("performance", [])


def load_noise_cost() -> dict[str, Any]:
    """Load measured noise cost (noise field); return an empty dict if missing or unparsable.

    Contents: {"method": "density_matrix", "noise": ..., "performance": [...],
    "infeasible_n": ...}, generated by scheduler.benchmark, so qshow and others
    can report the cost (4^n resources) from measured data in noisy scenarios
    rather than blindly choosing density_matrix.
    """
    return _load_benchmarks().get("noise", {})


def load_gpu_decision() -> dict[str, Any]:
    """Load the measured GPU decision table; return an empty dict if missing."""
    return _load_benchmarks().get("gpu", {}).get("decision", {})


def _gate_bucket(gate_count: int) -> str:
    """Bucket gate count for decision lookup."""
    if gate_count < 50:
        return "small"
    if gate_count < 200:
        return "medium"
    return "large"


def _depth_bucket(depth: int) -> str:
    """Bucket depth for decision lookup."""
    if depth < 20:
        return "shallow"
    if depth < 50:
        return "medium"
    return "deep"


def recommend_method(features: dict[str, Any], noise: bool = False) -> Recommendation:
    """Pick the best backend+method by checking the measured table, then cold-start rules.

    Returns a Recommendation(backend, method) — not just a method string — because
    the fastest backend/method pair varies by circuit (e.g., qiskit/statevector is
    100x faster than native/statevector for large circuits).

    Lookup chain:
    1. Detailed measured table (n|class|gate_bucket|depth_bucket) from benchmarks.json
    2. Legacy measured table (class -> {method, above_n})
    3. Cold-start rules (hardcoded defaults)
    """
    if noise:
        return Recommendation("native", "density_matrix")
    if features.get("requires_grad", False):
        return Recommendation("qiskit", "statevector")

    n = features["n"]
    gate_types = set(features["gate_types"])
    gate_count = features.get("gate_count", n)
    cls = decision_class(features)

    # 1. Try detailed measured table (data-driven, no hardcoded thresholds)
    measured = load_measured_decision()
    if measured:
        gc_bucket = _gate_bucket(gate_count)
        depth = features.get("depth", n)
        d_bucket = _depth_bucket(depth)
        family = features.get("family")
        # Try family-specific key first, then fall back to base key
        keys_to_try = []
        if family:
            keys_to_try.append(f"{n}|{family}|{cls}|{gc_bucket}|{d_bucket}")
        keys_to_try.append(f"{n}|{cls}|{gc_bucket}|{d_bucket}")
        for key in keys_to_try:
            entry = measured.get(key)
            if entry and "method" in entry:
                bm_key = entry["method"]  # e.g. "qiskit/statevector"
                if "/" in bm_key:
                    backend, method = bm_key.split("/", 1)
                else:
                    # Legacy format: just a method name
                    method = bm_key
                    backend = "native"
                # Check the method is eligible for this circuit's gate types
                if method in eligible_methods(gate_types):
                    return Recommendation(backend, method)

    # 2. Try legacy measured table
    if cls == "general":
        return Recommendation("qpanda", "statevector")
    legacy = measured.get(cls) if measured else None
    if legacy is None:
        legacy = _DEFAULT_DECISION.get(cls)
    if legacy and n >= legacy.get("above_n", 999):
        method = legacy["method"]
        backend = legacy.get("backend", "qiskit")
        if method in eligible_methods(gate_types):
            return Recommendation(backend, method)

    # 3. Cold-start fallback: QPanda is fastest for most small circuits
    return Recommendation("qpanda", "statevector")


def recommend_backend_gpu(features: dict[str, Any]) -> Recommendation:
    """Pick the best GPU backend for this circuit.

    Uses measured data from benchmarks.json when available; falls back to
    hardcoded decision tree based on circuit features.
    """
    # Try measured data first
    measured = load_gpu_decision()
    if measured:
        n = features["n"]
        entanglement = features.get("entanglement", "high")
        cls = "low_tw" if entanglement == "low" else "general"
        entry = measured.get(cls)
        if entry and n >= entry.get("above_n", 0):
            return Recommendation(entry["backend"], "gpu")
        # Default from measured: best backend for this class
        if entry:
            return Recommendation(entry["backend"], "gpu")

    # Fallback: hardcoded decision tree
    n = features["n"]
    entanglement = features.get("entanglement", "high")
    has_ctrl = features.get("has_ctrl", False)

    if entanglement == "low" and n >= 20:
        return Recommendation("tensorcircuit", "gpu")
    if has_ctrl:
        return Recommendation("qulacs", "gpu")
    if n <= 30:
        return Recommendation("qulacs", "gpu")
    return Recommendation("tensorcircuit", "gpu")


def recommend_backend_autodiff(features: dict[str, Any]) -> Recommendation:
    """Pick the best autodiff-capable backend for variational circuits.

    PennyLane and TensorCircuit both support automatic differentiation.
    Preference order: tensorcircuit (JAX, GPU-accelerated) > pennylane (parameter-shift).
    """
    n = features.get("n", 0)
    if n <= 20:
        return Recommendation("pennylane", "statevector")
    return Recommendation("tensorcircuit", "statevector")


class MemoryRegistry(BackendRegistry):
    """In-memory key -> backend mapping table."""

    def __init__(self, table: dict[str, str] | None = None) -> None:
        self.table: dict[str, str] = dict(table or {})

    def get_recommendation(self, features: dict[str, Any]) -> str | None:
        return self.table.get(features["key"])

    def __repr__(self) -> str:
        return f"MemoryRegistry({len(self.table)} entries)"


class FileRegistry(BackendRegistry):
    """Read-only static parameter table: load key -> backend mapping from a JSON file."""

    def __init__(self, path: str) -> None:
        with open(path, encoding="utf-8") as f:
            self.table: dict[str, str] = json.load(f)

    def get_recommendation(self, features: dict[str, Any]) -> str | None:
        return self.table.get(features["key"])

    def __repr__(self) -> str:
        return f"FileRegistry({len(self.table)} entries)"


class LocalCacheRegistry(BackendRegistry):
    """Local persistent cache with learning: records (key -> backend) pairs and
    timing data the user has run.

    When fine-tuning a circuit the key stays the same, so it directly hits the
    cache without re-deciding. report_result writes each run result (including
    timing) back to the file so the next query can pick the fastest backend.
    """

    def __init__(self, path: str) -> None:
        self.path: str = path
        self.table: dict[str, str] = {}
        # key -> {backend: [list of durations]}
        self.timings: dict[str, dict[str, list]] = {}
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
                if isinstance(data, dict):
                    if "table" in data:
                        self.table = data["table"]
                        self.timings = data.get("timings", {})
                    else:
                        # Legacy format: just key->backend
                        self.table = data

    def get_recommendation(self, features: dict[str, Any]) -> str | None:
        return self.table.get(features["key"])

    def get_best_backend(self, features: dict[str, Any]) -> str | None:
        """Pick the backend with the best average timing for this circuit key."""
        key = features.get("key")
        if key and key in self.timings:
            timings = self.timings[key]
            if timings:
                best = min(timings, key=lambda b: sum(timings[b]) / len(timings[b]))
                return best
        return None

    def report_result(
        self,
        features: dict[str, Any],
        backend_name: str,
        duration: float,
        memory: Any | None,
    ) -> None:
        key = features["key"]
        self.table[key] = backend_name
        if key not in self.timings:
            self.timings[key] = {}
        if backend_name not in self.timings[key]:
            self.timings[key][backend_name] = []
        self.timings[key][backend_name].append(duration)
        # Keep only last 10 timings per backend
        self.timings[key][backend_name] = self.timings[key][backend_name][-10:]
        self._save()

    def _save(self) -> None:
        data = {"table": self.table, "timings": self.timings}
        with open(self.path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    def __repr__(self) -> str:
        return f"LocalCacheRegistry({len(self.table)} entries, {self.path})"
